In [1]:
import numpy as np


In [34]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.mat([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
#1.取一个元素时，数组和矩阵返回值一样
a1 = a[1,1]
a1

5

In [28]:
#3. 取 0，2行，数组和矩阵返回值一样
a3 = a[[0,2]]
# 去 0, 2行的 第二列 
a32 = a[[0,2],2]
a3, a32

(array([[1, 2, 3],
        [7, 8, 9]]),
 array([3, 9]))

In [16]:
#先取0，1行，再取0，1列. 直接一起写行列是错误的如：a3=a[[0,1]，[0,1]]
a33 = a3[:,[0,2]]
a33


array([[1, 3],
       [7, 9]])

In [17]:
b3 = b[[0,2]]
b3

matrix([[1, 2, 3],
        [7, 8, 9]])

In [53]:
b33 = b[:,[0,2]]
b33


matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [54]:
array = np.array([1, 2, 3, 4, 5, 6])
for x in array:
    print(x)

1
2
3
4
5
6


In [60]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# print rows first 
for i in array:
    print(i)
    # then print each element in the rows
    for j in i:
        print(j)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [70]:
# the nditer method can iterate all elements in a matrix and array
for i in np.nditer(b):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [73]:
array_3d = np.array([[[1], [2]], [[3], [4]]])

for i in np.nditer(array_3d):
    print(i)

1
2
3
4


In [74]:
# This function prints the value of the corresponding index number.
array = np.array([1, 2, 3, 4, 5, 6])

for i, x in np.ndenumerate(array):
    print(i, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6


In [76]:
# apply it on a 2-d array
array_2d = np.array([[1,2,3,4], [5,6,7,8]])

for i, x in np.ndenumerate(array_2d):
    print(i, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [82]:
for i, x in np.ndenumerate(b):
    print(i, x)

b.shape, a.shape, type(b), type(a)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9
(3, 0) 10
(3, 1) 11
(3, 2) 12


((4, 3), (3, 3), numpy.matrix, numpy.ndarray)

In [93]:
# print a 3-d array 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print('x values:', x)
    for y in x:
        print('y values:', y)
        for z in y:
            print('z values:', z)

x values: [[1 2 3]
 [4 5 6]]
y values: [1 2 3]
z values: 1
z values: 2
z values: 3
y values: [4 5 6]
z values: 4
z values: 5
z values: 6
x values: [[ 7  8  9]
 [10 11 12]]
y values: [7 8 9]
z values: 7
z values: 8
z values: 9
y values: [10 11 12]
z values: 10
z values: 11
z values: 12


1
2
3
4
5
6
7
8
9
10
11
12
